name: habitta
description: "A new Flutter project."
publish_to: 'none' # Prevents unintended publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.1
  google_fonts: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon_v1_1.png"  # Put your icon image here (square recommended)

flutter:
  uses-material-design: true

  # Uncomment and add asset paths if you have images/fonts
  # assets:
  #   - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
